// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolTemp.WPF.Models;

#nullable disable

namespace ToolTemp.WPF.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToolTemp.WPF.Models.ActiveType", b =>
                {
                    b.Property<int>("activeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("activeid");

                    b.ToTable("ActiveType");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.BusDataTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressMachine")
                        .HasColumnType("int");

                    b.Property<int>("Baudrate")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdMachine")
                        .HasColumnType("int");

                    b.Property<int?>("IdStyle")
                        .HasColumnType("int");

                    b.Property<bool>("IsWarning")
                        .HasColumnType("bit");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.Property<int>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sensor_Typeid")
                        .HasColumnType("int");

                    b.Property<string>("Sensor_ant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sensor_kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temp")
                        .HasColumnType("float");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dv_BusDataTemp");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.Controlcode", b =>
                {
                    b.Property<int>("codeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codeid"));

                    b.Property<int>("activeid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codetypeid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("factor")
                        .HasColumnType("float");

                    b.Property<decimal?>("high")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ifcal")
                        .HasColumnType("int");

                    b.Property<int?>("ifshow")
                        .HasColumnType("int");

                    b.Property<decimal?>("low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("typeid")
                        .HasColumnType("int");

                    b.HasKey("codeid");

                    b.ToTable("controlcode");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.Device", b =>
                {
                    b.Property<string>("DevId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActiveId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("DevId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.DvFactoryAssembling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assembling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dv_FactoryAddress_Configs");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dv_Factory_Configs");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<int>("Baudrate")
                        .HasColumnType("int");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dv_Machine_Temp");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.SensorData", b =>
                {
                    b.Property<int>("logid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logid"));

                    b.Property<int>("codeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime2");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("logid");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("ToolTemp.WPF.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CompensateVaild")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Compensate_Vaild");

                    b.Property<decimal>("DeMax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoleMax");

                    b.Property<decimal>("DeMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoleMin");

                    b.Property<string>("Devid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiayMax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ShoesMax");

                    b.Property<decimal>("GiayMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ShoesMin");

                    b.Property<string>("NameStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardTemp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Standard_temp");

                    b.HasKey("Id");

                    b.ToTable("dv_style");
                });
#pragma warning restore 612, 618
        }
    }
}
